//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPPER_AADD_navarro_contin.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marcas
    {
        public Marcas()
        {
            this.Modelos = new HashSet<Modelos>();
        }
    
        public int id_marca { get; set; }
        public string nombre_marca { get; set; }
    
        public virtual ICollection<Modelos> Modelos { get; set; }
    }
}
