//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPPER_AADD_navarro_contin.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelos
    {
        public Modelos()
        {
            this.Vehiculos = new HashSet<Vehiculos>();
        }
    
        public int id_modelo { get; set; }
        public string nombre_modelo { get; set; }
        public int id_marca { get; set; }
    
        public virtual Marcas Marcas { get; set; }
        public virtual ICollection<Vehiculos> Vehiculos { get; set; }
    }
}
