//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPPER_AADD_navarro_contin.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculos
    {
        public int id_vehiculo { get; set; }
        public int id_modelo { get; set; }
        public string color { get; set; }
        public decimal precio { get; set; }
        public Nullable<int> anio { get; set; }
        public Nullable<bool> disponible { get; set; }
    
        public virtual Modelos Modelos { get; set; }
    }
}
